repos:
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        stages: [commit]
        language: system
        entry: make test
      - id: lint
        name: lint
        stages: [commit]
        language: system
        entry: make lint
      - id: clean
        name: clean
        stages: [commit]
        language: system
        entry: make clean
